services:
  postgres:
    image: postgres:17
    container_name: movies_db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
